spring:
  datasource:
    dynamic:
      primary: adx_autotag_service
      strict: false
      datasource:
        adx_autotag_service:
          url: jdbc:mysql://172.18.99.77:3306/adx_autotag_service_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&&useLegacyDatetimeCode=false
          username: adx_test
          password: Adx_test@2021
      druid:
        initialSize: 5
        minIdle: 2
        maxActive: 50
        max-wait: 3000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        remove-abandoned: false
  kafka:
    bootstrap-servers: 172.18.99.78:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    database: 4
    host: 172.18.99.77
    password: D@taeye_test
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: 1s
logstash: 172.18.99.1:9600