spring:
  datasource:
    dynamic:
      primary: adx_autotag_service
      strict: false
      datasource:
        adx_autotag_service:
          url: jdbc:mysql://10.1.9.5:3306/adx_autotag_service?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&&useLegacyDatetimeCode=false
          username: root
          password: DataEye2020@mysql
      druid:
        initialSize: 5
        minIdle: 2
        maxActive: 50
        max-wait: 3000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        remove-abandoned: false
  kafka:
    bootstrap-servers: 10.1.9.11:9092,10.1.9.12:9092,10.1.9.13:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    database: 4
    host: 10.1.9.5
    password: dataeye@redis
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: 1s

logstash: 10.1.9.47:9600

