spring:
  datasource:
    dynamic:
      primary: adx_autotag_service
      strict: false
      datasource:
        adx_autotag_service:
          url: jdbc:mysql://pc-wz96077e77bktj328.rwlb.rds.aliyuncs.com:3306/adx_autotag_service?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&&useLegacyDatetimeCode=false
          username: polardb_user
          password: pUser@2016#
      druid:
        initialSize: 5
        minIdle: 2
        maxActive: 50
        max-wait: 3000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        remove-abandoned: false
  kafka:
    bootstrap-servers: 172.18.248.82:9092,172.18.248.83:9092,172.18.248.84:9092,172.18.248.85:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    database: 4
    host: r-wz9x9aysewffwvvly0.redis.rds.aliyuncs.com
    password: Dc@dataeye2#
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 20
        max-wait: 1s

logstash: adx-logstash-1.dataeye.com:9600